name: Kutipanku CI/CD

on:
  push:
    branches: [master]

jobs:
  test_web:
    runs-on: ubuntu-latest
    name: Install Dependency & Test - Web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup and run tests
        working-directory: ./
        run: |
          rm -rf node-modules
          yarn install
          yarn test

  deploy:
    runs-on: ubuntu-latest
    name: Deploy - Web
    needs: [test_web]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_WEB_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
